# yaml-language-server: $schema=https://cdn.jsdelivr.net/gh/prefix-dev/recipe-format/schema.json

schema_version: 1

context:
  name: libvalkey
  version: "0.1.0"

package:
  name: "${{ name }}"
  version: "${{ version }}"

source:
  url: https://github.com/valkey-io/libvalkey/archive/refs/tags/${{ version }}.zip
  sha256: "118e4cf50daf32645d267740f431e81c91bc85f332ea14a8051ddab59bba79c5"

build:
  number: 2
  script:
    content:
      - if: linux
        then: cmake ${CMAKE_ARGS} -DENABLE_TLS=1 -DENABLE_RDMA=1 .
      - if: osx
        then: cmake ${CMAKE_ARGS} -DENABLE_TLS=1 .
      - if: win
        then: "cmake -DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX% %SRC_DIR%"
      - if: win
        then:
          - cmake --build %SRC_DIR%
          - cmake --install %SRC_DIR%
        else:
          - cmake --build .
          - cmake --install .

requirements:
  build:
    - nushell
    - "${{ compiler('c') }}"
    - ninja
    - cmake

  host:
    - openssl>=3
    - if: linux
      then: rdma-core

tests:
  - script:
      - if: unix
        then:
          - test -f ${PREFIX}/include/valkey/valkey.h
          - test -f ${PREFIX}/lib/libvalkey${SHLIB_EXT}

about:
  license: MIT
  license_file:
    - COPYING
  summary: Valkey client library in C
  description: |
    this package is build from
    [https://github.com/trim21/libvalkey-feedstock](https://github.com/trim21/libvalkey-feedstock)
  homepage: https://github.com/valkey-io/libvalkey
  repository: https://github.com/valkey-io/libvalkey
