name: build conda packages

on:
  workflow_call:

jobs:
  build:
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-24.04"
          - "ubuntu-24.04-arm"
          - "windows-2022"
          - "macos-13"
          - "macos-15"
    steps:
      - uses: actions/checkout@v4

      - uses: jaxxstorm/action-install-gh-release@v2.1.0
        with:
          repo: prefix-dev/rattler-build
          tag: "v0.41.0"

      - run: rm C:/Strawberry/perl/bin -rf
        if: ${{ runner.os == 'Windows' }}
        shell: bash

      - uses: TheMrMilchmann/setup-msvc-dev@v3
        if: ${{ runner.os == 'Windows' }}
        with:
          arch: x64

      - run: >-
          rattler-build build
          --wrap-log-lines=false
          --log-style=plain
          --skip-existing=all
          --output-dir=./output
          --channel=conda-forge
          --channel=https://repo.prefix.dev/trim21-pkgs
          --verbose
          --recipe-dir=recipe

      - run: ls ./output/

      - uses: actions/upload-artifact@v4
        with:
          name: "conda-${{ runner.os }}-${{ runner.arch }}"
          path: ./output/*/libvalkey-*.conda
